### ISSUE TITLE
Failed to build on ubuntu20.04 with gcc 12.3.0

### ISSUE THREAD

**Issue by wnpllrzodiac** [dengxiayehu/flvpusher#6]
```
/data/git/flvpusher/sources/hls/hls_segmenter.cpp:225:7: error: reference to ‘byte’ is ambiguous
  225 |       byte *pkt_data;
      |       ^~~~
In file included from /data/tools/gcc-12/include/c++/12.3.0/cmath:42,
                 from /data/tools/gcc-12/include/c++/12.3.0/math.h:36,
                 from /data/git/flvpusher/sources/hls/hls_segmenter.cpp:1:
/data/tools/gcc-12/include/c++/12.3.0/bits/cpp_type_traits.h:406:30: note: candidates are: ‘enum class std::byte’
  406 |   enum class byte : unsigned char;
      |                              ^~~~
In file included from /data/git/flvpusher/sources/xutil/xutil.h:7,
                 from /data/git/flvpusher/sources/xutil/xlog.h:22,
                 from /data/git/flvpusher/sources/hls/hls_segmenter.h:4,
                 from /data/git/flvpusher/sources/hls/hls_segmenter.cpp:8:
/data/git/flvpusher/sources/xutil/xtype.h:8:17: note:                 ‘typedef uint8_t byte’
    8 | typedef uint8_t byte;
      |                 ^~~~
/data/git/flvpusher/sources/hls/hls_segmenter.cpp:225:13: error: ‘pkt_data’ was not declared in this scope; did you mean ‘pkt_dts’?
  225 |       byte *pkt_data;
      |             ^~~~~~~~
      |             pkt_dts
```
